# Install VS Code extension: rest-client 
# URL: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@Host=http://localhost:8888/api/v1
@AccessToken=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ2ZDRlYmExLTRkOTMtNDViNC1hNzRjLTMzYWI2NTdlM2RhZiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ0eXBlIjoiQWRtaW4iLCJpYXQiOjE3MTkzNjEzMjksImV4cCI6MTcxOTQ0NzcyOX0.OeyuI2enVe2-tb0pLZvSpYG5MTGErBWW9l1XOz5c6O5TJuFhXan-Mlv-iv59C1RxAOpZAebmjFWERV-YRE56sWRKlZRl4ZQW3XGwUKaIdK6T6-vE-Q5HR1Aucfnmr5wrr_T-GP2kBp6keNeir7pkiVAPrGNBfyP2_TGs-ovzwT67PdkieNiRVjVV4N224wQf8cbw9qw0rmDchIYgXCFxgs2zp6J6ZcAelz9ufGdDcASi75ijMWk_eNo9kiZC6v_NfZMiWK1Kk0qN3zoSgcBx9Hxogg9qOzG13mB2ljg85QLFDq0tROAG8VA2yjzIJ_mWmsdhUIubEZOMxVmiFnOAFA
@GroupA=fdab7a99-2c38-444b-bcb3-f7cef61c275b
@GroupB=be1fcb4e-caf9-41c2-ac27-c06fa24da36a
@User1=c4644733-deea-47d8-b35a-86f30ff9618e
@User2=d700932c-4a11-427f-9183-d6c4b69368f9

###########################################
# Auth

### /auth/login
POST {{Host}}/auth/login
content-type: application/json

{
    "email": "admin@example.com",
    "password": "Password@1234"
}


### /_authcheck
GET {{Host}}/_authcheck
Authorization: Bearer {{AccessToken}}


### /auth/sign-up
POST {{Host}}/auth/sign-up
content-type: application/json

{
    "email": "johnsmith@foobar.net",
    "password": "Password@1234",
    "firstName": "John",
    "lastName": "Smith",
    "groupName": "",
    "tos": "2024-04-16"
}


### /_authcheck
GET {{Host}}/auth/verify-email/000000
Authorization: Bearer {{AccessToken}}


### /auth/forgot
POST {{Host}}/auth/forgot
content-type: application/json

{
    "email": "johnsmith@foobar.net"
}


### /auth/get-user-by-reset-key/:passwordResetKey
GET {{Host}}/auth/get-user-by-reset-key/000000
Authorization: Bearer {{AccessToken}}


### /auth/reset
POST {{Host}}/auth/reset
content-type: application/json

{
    "email": "johnsmith@foobar.net",
    "password": "new-password-4321",
    "passwordResetKey": "000000"
}


### /auth/get-user-by-invite-key/:inviteKey
GET {{Host}}/auth/get-user-by-invite-key/000000
Authorization: Bearer {{AccessToken}}


### /auth/invite
POST {{Host}}/auth/invite
content-type: application/json

{
    "inviteKey": "000000",
    "email": "johnsmith@foobar.net",
    "password": "password@1234",
    "firstName": "John",
    "lastName": "Smith",
    "tos": "2024-04-16"
}


###########################################
# User

### /user
GET {{Host}}/user
Authorization: Bearer {{AccessToken}}


### /user
POST {{Host}}/user
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "firstName": "Alex",
    "lastName": "Jones"
}


### /user/update-password
POST {{Host}}/user/update-password
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "password": "Password@1234",
    "newPassword": "NewPassword!4321"
}


###########################################
# Group

### /groups/:groupID
GET {{Host}}/groups/{{GroupA}}?with=users
Authorization: Bearer {{AccessToken}}


### /groups/:groupID
POST {{Host}}/groups/{{GroupA}}
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "New Group Name"
}


### /groups/:groupID/users/invite
POST {{Host}}/groups/{{GroupA}}/users/invite
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "email": "foobar@gamil.com"
}   


### /groups/:groupID/users/:userID/set-role
POST {{Host}}/groups/{{GroupA}}/users/{{User2}}/set-role
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "role": "Admin"
}   


### /groups/:groupID/users/:userID  
DELETE {{Host}}/groups/{{GroupA}}/users/{{User2}}
Authorization: Bearer {{AccessToken}}


###########################################
# PRBox

@pRBoxID=d8985d0d-078b-41d2-bb2e-61bb71413976

### GET /prboxes
GET {{Host}}/prboxes
Authorization: Bearer {{AccessToken}}

### GET /prboxes/:pRBoxID
GET {{Host}}/prboxes/{{pRBoxID}}
Authorization: Bearer {{AccessToken}}

### POST /prboxes
POST {{Host}}/prboxes
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "New Book"
}

### POST /prboxes/:pRBoxID
POST {{Host}}/prboxes/{{pRBoxID}}
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "Updated Book Name"
}

### DELETE /prboxes/:pRBoxID
DELETE {{Host}}/prboxes/{{pRBoxID}}
Authorization: Bearer {{AccessToken}}


###########################################
# Package

@packageID=0b830fd7-fa57-4d86-9432-d8bf3c40dc77

### GET /packages
GET {{Host}}/packages
Authorization: Bearer {{AccessToken}}

### GET /packages/:packageID
GET {{Host}}/packages/{{packageID}}
Authorization: Bearer {{AccessToken}}

### POST /admin/items
POST {{Host}}/admin/items
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "New Book"
}

### POST /packages/:packageID
POST {{Host}}/packages/{{packageID}}
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "Updated Book Name"
}

### DELETE /packages/:packageID
DELETE {{Host}}/packages/{{packageID}}
Authorization: Bearer {{AccessToken}}


###########################################
# Charges

@chargesID=05447dd7-1035-49aa-bb3e-719cd4712752

### GET /charges
GET {{Host}}/charges
Authorization: Bearer {{AccessToken}}

### GET /charges/:chargesID
GET {{Host}}/charges/{{chargesID}}
Authorization: Bearer {{AccessToken}}

### POST /charges
POST {{Host}}/charges
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "New Book"
}

### POST /charges/:chargesID
POST {{Host}}/charges/{{chargesID}}
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "Updated Book Name"
}

### DELETE /charges/:chargesID
DELETE {{Host}}/charges/{{chargesID}}
Authorization: Bearer {{AccessToken}}
